arb-dir: lib/core/localization/l10n
template-arb-file: app_fr.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/core/localization/l10n
untranslated-messages-file: untranslated_messages.txt
preferred-supported-locales: [fr, en, de]
