// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// Supported platforms: web, Android, iOS, macOS.
// Windows and Linux are not configured for Lucy phase 1 — run `flutterfire configure`
// with those platforms if desktop support is added later.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_ru5aiJCHOpQ0buUoqi5W17fRARJKSH4',
    appId: '1:915801010147:web:75f0dcb822ea0a978a3ad6',
    messagingSenderId: '915801010147',
    projectId: 'lucy-7504c',
    authDomain: 'lucy-7504c.firebaseapp.com',
    storageBucket: 'lucy-7504c.firebasestorage.app',
    measurementId: 'G-GYR878X776',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFnXBaVPCXLxfMlWhVz_X_7Uh_7HYuTp0',
    appId: '1:915801010147:android:866498945967265a8a3ad6',
    messagingSenderId: '915801010147',
    projectId: 'lucy-7504c',
    storageBucket: 'lucy-7504c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOvThAFVdJFTBTuiRnqyS9aIrAHD7SJ1k',
    appId: '1:915801010147:ios:17c805a6dbaec3d08a3ad6',
    messagingSenderId: '915801010147',
    projectId: 'lucy-7504c',
    storageBucket: 'lucy-7504c.firebasestorage.app',
    iosClientId:
        '915801010147-t19l9e4ukna7f179h2oajk5qv5nkbo6g.apps.googleusercontent.com',
    iosBundleId: 'com.lucy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOvThAFVdJFTBTuiRnqyS9aIrAHD7SJ1k',
    appId: '1:915801010147:ios:17c805a6dbaec3d08a3ad6',
    messagingSenderId: '915801010147',
    projectId: 'lucy-7504c',
    storageBucket: 'lucy-7504c.firebasestorage.app',
    iosClientId:
        '915801010147-t19l9e4ukna7f179h2oajk5qv5nkbo6g.apps.googleusercontent.com',
    iosBundleId: 'com.lucy.app',
  );
}
